server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: misfichas-api

  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/misfichasDB
#    username: admin
#    password: Admin123!
#    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: INFO